/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp2pbo2021;
import java.awt.image.BufferedImage;
import java.net.URL;
import java.io.IOException;
import java.awt.Graphics2D;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableCellRenderer;
/**
 *
 * @author Asus
 */

//Saya Farhan Nurzaman mengerjakan TP2PBO dalam mata kuliah DPBO untuk
//keberkahan-Nya, maka saya tidak melakukan kecurangan seperti yang telah
//dispesifikasikan. Aamiin.
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private javax.swing.JLayeredPane layeredPanel;
    private javax.swing.JLabel labelMerk;
    private javax.swing.JTextField textMerk;
    private javax.swing.JLabel labelPlat;
    private javax.swing.JTextField textPlat;
    private javax.swing.JLabel labelWarna;
    private javax.swing.JTextField textWarna;
    private javax.swing.JLabel labelJenis;
    private javax.swing.JComboBox<String> boxJenis;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel picture;
    private BufferedImage myPicture;
    private javax.swing.JTable tabelData;
    private String header[] = new String[]{"No", "Merk", "Plat", "Warna","Jenis"};
    private javax.swing.table.DefaultTableModel tabel;
    private javax.swing.JScrollPane scrollPanel;
    private ArrayList<Mobil> listMobil;
    public Menu() {
        initComponents();
        listMobil = new ArrayList<Mobil>();
        // Dibikin manual biar bisa ditumpuk
        
        initPanelForm();
        initPanelInfo();
        initPanelTable();
        // INIT COMPONENTS
        switchForm(true);
        switchInfo(false);
        switchTable(false);
        layeredPanel.add(scrollPanel);
        this.add(layeredPanel);
        this.setLayout(null);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnForm = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(400, 600));
        setResizable(false);

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA MOBIL TP2");

        btnForm.setBackground(new java.awt.Color(51, 51, 51));
        btnForm.setForeground(new java.awt.Color(204, 204, 204));
        btnForm.setText("Form");
        btnForm.setBorderPainted(false);
        btnForm.setFocusPainted(false);
        btnForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFormMouseExited(evt);
            }
        });
        btnForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formPerformed(evt);
            }
        });

        btnTable.setBackground(new java.awt.Color(51, 51, 51));
        btnTable.setForeground(new java.awt.Color(204, 204, 204));
        btnTable.setText("Table");
        btnTable.setBorderPainted(false);
        btnTable.setFocusPainted(false);
        btnTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTableMouseExited(evt);
            }
        });
        btnTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablePerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(51, 51, 51));
        btnInfo.setForeground(new java.awt.Color(204, 204, 204));
        btnInfo.setText("Info");
        btnInfo.setBorderPainted(false);
        btnInfo.setFocusPainted(false);
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
        });
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(btnForm)
                .addGap(31, 31, 31)
                .addComponent(btnTable)
                .addGap(30, 30, 30)
                .addComponent(btnInfo)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnForm)
                    .addComponent(btnTable)
                    .addComponent(btnInfo))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Submit.setBackground(new java.awt.Color(51, 51, 51));
        Submit.setForeground(new java.awt.Color(204, 204, 204));
        Submit.setText("Submit");
        Submit.setBorderPainted(false);
        Submit.setFocusPainted(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Submit)
                        .addGap(149, 149, 149))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void initPanelForm(){
        layeredPanel = new javax.swing.JLayeredPane();
        labelMerk = new javax.swing.JLabel();
        textMerk = new javax.swing.JTextField();
        labelPlat = new javax.swing.JLabel();
        textPlat = new javax.swing.JTextField();
        labelWarna = new javax.swing.JLabel();
        textWarna = new javax.swing.JTextField();
        labelJenis = new javax.swing.JLabel();
        boxJenis = new javax.swing.JComboBox<>();
        
        layeredPanel.setBounds(0,160,400,400);
        layeredPanel.setBackground(java.awt.Color.red);
        labelMerk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        // Merk
        labelMerk.setBounds(70,40,50,30);
        labelMerk.setText("Merk ");
        labelMerk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMerk.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        textMerk.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textMerk.setBounds(120,45,200,20);
        textMerk.setText("");
        // Plat
        labelPlat.setBounds(70,80,50,30);
        labelPlat.setText("Plat ");
        labelPlat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPlat.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        textPlat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textPlat.setBounds(120,85,200,20);
        textPlat.setText("");
        // Warna
        labelWarna.setBounds(70,120,50,30);
        labelWarna.setText("Warna ");
        labelWarna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWarna.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        textWarna.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textWarna.setBounds(120,125,200,20);
        textWarna.setText("");
        // Jenis
        labelJenis.setBounds(70,160,50,30);
        labelJenis.setText("Jenis ");
        labelJenis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJenis.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        boxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Biasa", "Balap", "Sport", "Truk" }));
        boxJenis.setBounds(120,160,80,30);
        layeredPanel.add(labelMerk);
        layeredPanel.add(textMerk);
        layeredPanel.add(labelPlat);
        layeredPanel.add(textPlat);
        layeredPanel.add(labelWarna);
        layeredPanel.add(textWarna);
        layeredPanel.add(labelJenis);
        layeredPanel.add(boxJenis);
        // Submit buttons
        Submit.setBounds(8,375,370,30);
    }
    public void initPanelInfo(){
        try {                
           myPicture = javax.imageio.ImageIO.read(new URL("https://github.com/farhannz/TP2PBO2021/raw/main/foto.jpg"));
       } catch (IOException ex) {
            // handle exception...
            System.out.print(ex);
       }
        java.awt.Image tmp = myPicture.getScaledInstance(180, 120, BufferedImage.SCALE_SMOOTH);
        BufferedImage resized = new BufferedImage(180,120,BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = resized.createGraphics();
        g2d.drawImage(tmp,0,0,null);
        g2d.dispose();
        myPicture = resized;
        picture = new javax.swing.JLabel(new javax.swing.ImageIcon(myPicture));
        nama = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        
        picture.setBounds(100,0,180,120);
        nama.setBounds(100,150,180,30);
        nim.setBounds(100,180,180,30);
        nama.setText("Nama : Farhan Nurzaman");
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nama.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        nim.setText("NIM : 1904908");
        nim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nim.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        layeredPanel.add(picture);
        layeredPanel.add(nama);
        layeredPanel.add(nim);
    }
    public void initPanelTable(){
        tabel = new javax.swing.table.DefaultTableModel(header,0);
        tabelData = new javax.swing.JTable(tabel);
        tabelData.setModel(tabel);
        tabelData.setBounds(5,0,380,400);
//        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
//        center.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        tabelData.setDefaultRenderer(String.class, center);
        scrollPanel = new javax.swing.JScrollPane(tabelData);
        scrollPanel.setBounds(5,0,380,400);
    }
    public void ambilData(){
        String host = "jdbc:mysql://localhost:3306/tp2Mobil?useTimezone=true&serverTimezone=UTC";
        String username ="root";
        String pass = "";
        String query = "SELECT * from mobil";
        try{
            Connection con = DriverManager.getConnection(host,username,pass);
            Statement statement = con.createStatement();
            ResultSet result = statement.executeQuery(query);
           
            ResultSetMetaData rsmd = result.getMetaData();
            int column = rsmd.getColumnCount();
            tabel.setRowCount(0);
            while(result.next()){
                tabel.setRowCount(0);
                String tampil = "";
                String[] dataKolom = new String[4];
                //| 0  | 1  |  2  |  3  |
                //|Merk|Plat|Warna|Jenis|
                for(int i = 2; i<=column;++i){
                    dataKolom[i-2] = result.getString(i);
                }
                listMobil.add(new Mobil(dataKolom[0],dataKolom[1],dataKolom[2],dataKolom[3]));
//                System.out.println(dataKolom[0]);
//                System.out.println(dataKolom[1]);
//                System.out.println(dataKolom[2]);
//                System.out.println(dataKolom[3]);
            }
            for(int i = 0;i<listMobil.size();++i){
                Object[] objs  = {
                    i+1,
                    listMobil.get(i).getMerk(),
                    listMobil.get(i).getPlat(),
                    listMobil.get(i).getWarna(),
                    listMobil.get(i).getJenis()
                };
                tabel.addRow(objs);
            }
            scrollPanel.setBounds(5,160,380,400);
            add(scrollPanel);
            listMobil.clear();
        }
        catch(SQLException e){
            //
            e.printStackTrace();
        }
    }
    public void switchForm(boolean value){
        labelMerk.setVisible(value);
        labelPlat.setVisible(value);
        labelWarna.setVisible(value);
        labelJenis.setVisible(value);
        labelJenis.setVisible(value);
        textMerk.setVisible(value);
        textPlat.setVisible(value);
        textWarna.setVisible(value);
        boxJenis.setVisible(value);
        Submit.setVisible(value);
    }
    public void switchTable(boolean value){
        ambilData();
        scrollPanel.setVisible(value);
    }
    public void switchInfo(boolean value){
        nama.setVisible(value);
        nim.setVisible(value);
        picture.setVisible(value);
    }
    
    public static void infoBox(String infoMessage, String titleBar)
    {
        javax.swing.JOptionPane.showMessageDialog(null, infoMessage, titleBar, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    private void infoPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPerformed
        // TODO add your handling code here:
//        infoBox("AYAYAYAYYAYA","OYOYOYOYOOY");
        switchInfo(true);
        switchForm(false);
        switchTable(false);
    }//GEN-LAST:event_infoPerformed

    private void tablePerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablePerformed
        // TODO add your handling code here:
        
//        infoBox("AYAYAYAYYAYA","OYOYOYOYOOY");
        switchInfo(false);
        switchForm(false);
        switchTable(true);
    }//GEN-LAST:event_tablePerformed

    private void formPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formPerformed
        // TODO add your handling code here:
//        infoBox("AYAYAYAYYAYA","OYOYOYOYOOY");
        switchForm(true);
        switchInfo(false);
        switchTable(false);
    }//GEN-LAST:event_formPerformed

    private void btnFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormMouseEntered
        // TODO add your handling code here:
        btnForm.setBackground(new java.awt.Color(204, 204, 204));
        btnForm.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btnFormMouseEntered

    private void btnFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormMouseExited
        // TODO add your handling code here:
        btnForm.setBackground(new java.awt.Color(51, 51, 51));
        btnForm.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_btnFormMouseExited

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered
        // TODO add your handling code here:
        btnInfo.setBackground(new java.awt.Color(204, 204, 204));
        btnInfo.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btnInfoMouseEntered

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited
        // TODO add your handling code here:
        btnInfo.setBackground(new java.awt.Color(51, 51, 51));
        btnInfo.setForeground(new java.awt.Color(204, 204, 204));
    }//GEN-LAST:event_btnInfoMouseExited

    private void btnTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTableMouseEntered
        // TODO add your handling code here:
        btnTable.setBackground(new java.awt.Color(204, 204, 204));
        btnTable.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btnTableMouseEntered

    private void btnTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTableMouseExited
        // TODO add your handling code here:
        btnTable.setBackground(new java.awt.Color(51, 51, 51));
        btnTable.setForeground(new java.awt.Color(204, 204, 204));
        
    }//GEN-LAST:event_btnTableMouseExited

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        String Merk = textMerk.getText();
        String Plat = textPlat.getText();
        String Warna = textWarna.getText();
        String Jenis = (String)boxJenis.getSelectedItem();
        String host = "jdbc:mysql://localhost:3306/tp2mobil?useTimezone=true&serverTimezone=UTC";
        String username ="root";
        String pass = "";
        String query = "";
        if(Merk != "" && Plat != "" && Warna != "" && Jenis != ""){
            query = "INSERT INTO mobil(merk,plat,warna,jenis) value(";
            query += '"' + Merk+ '"' +",";
            query += '"' + Plat  + '"'  +",";
            query += '"' + Warna + '"' +",";
            query += '"' + Jenis + '"' +")";
            System.out.println(query);            
            try{
                Connection con = DriverManager.getConnection(host,username,pass);
                Statement statement = con.createStatement();
                int result = statement.executeUpdate(query);
                infoBox("Berhasil memasukkan data","Message");

            }
            catch(SQLException e){
                //
                infoBox("Gagal memasukkan data","Message");
                e.printStackTrace();
            }
        }
        else{
            infoBox("Data tidak boleh ada yang kosong!", "Alert");
        }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JButton btnForm;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
